apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jhipster-operator
  namespace: jhipster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jhipster-operator
subjects:
- kind: ServiceAccount
  name: jhipster-operator
  namespace: jhipster