apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhipster-operator
  labels:
    app: jhipster-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhipster-operator
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: jhipster-operator
    spec:
      containers:
      - name: jhipster-operator
        # For KIND
        image: jhipster-operator
        imagePullPolicy: Never
        ##image: salaboy/jhipster-operator
        ##imagePullPolicy: Always
        ports:
        - containerPort: 8080
      serviceAccountName: jhipster-operator