apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: applications.alpha.k8s.jhipster.tech
spec:
  group: alpha.k8s.jhipster.tech
  version: v1 
  scope: Namespaced
  names:
    plural: applications 
    singular: application
    kind: Application 
    shortNames:
    - jh
  additionalPrinterColumns:
    - name: STATUS
      type: string
      description: The Status of the App
      JSONPath: .spec.status
    - name: URL
      type: string
      description: The URL of the App
      JSONPath: .spec.url    