apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: registries.alpha.k8s.jhipster.tech
spec:
  group: alpha.k8s.jhipster.tech
  version: v1 
  scope: Namespaced 
  names:
    plural: registries
    singular: registry
    kind: Registry
    shortNames:
    - r
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            serviceName:
              type: string
          required:
            - serviceName